# Generated by Django 5.0.4 on 2024-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodb',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
    ]
